### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by s1037989** [jhthorsen/app-git-ship#11]
Where all does author get used?  One place is Makefile.PL.  And it grabs the author of the user that runs git ship build.  For example this very module...  Written by @jhthorsen but if I'm an accepted co-author / co-maintainer then I can git ship it myself, but then I become listed as the author.  Is that right?

I'm thinking a solution would be to add an author = attribute to .ship.conf that would allow overriding authorship from git's config author.

**Comment by jhthorsen** [comment]
I haven't read all the posts on the different CPAN roles in depth, so I really don't know the correct answer.

But adding author to .ship.conf sounds good to me!

**Comment by s1037989** [comment]
Can you link me to these posts you're talking about?  I'd be happy to read them.  As it stands, I don't know what you're talking about, so I couldn't possibly find it on my own.  :)

Great...  I'll take care of adding author to .ship.conf!

**Comment by jhthorsen** [comment]
Here you go:
- http://perlweekly.com/archive/238.html
- http://neilb.org/2016/02/13/it-takes-a-community.html
- https://rjbs.manxome.org/rubric/entry/2096
- http://wollmers-perl.blogspot.no/2016/02/credit-first-or-last-uploader-on.html

**Comment by jhthorsen** [comment]
Closing this because it's old.
