### ISSUE TITLE
Incorrect statement in doc regarding Changes file

### ISSUE THREAD

**Issue by s1037989** [jhthorsen/app-git-ship#13]
> Changes is automatically created for you if you set the class to
App::git::ship::perl

[L350](https://github.com/jhthorsen/app-git-ship/blob/master/lib/App/git/ship.pm#L350)

I don't think think this is a true statement.  When I follow the quick-start guide, I am unable to be successful until I create my own Changes file (with the text "Not Released" as the timestamp).

**Comment by jhthorsen** [comment]
I don't think this is the case. At least not anymore, because if I remove this line, then the test suite fails:

https://github.com/jhthorsen/app-git-ship/blob/master/lib/App/git/ship/perl.pm#L163
