### ISSUE TITLE
Need to update copyright date in POD

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/app-git-ship#2]
Whenever a change is done in a new year, the copyright part should be updated in the POD.

Example:

```
Copyright (C) 2011, Jan Henning Thorsen
```

...would become:

```
Copyright (C) 2011-2015, Jan Henning Thorsen
```

**Comment by jhthorsen** [comment]
Can you do this change @s1037989? I'm not sure what is correct...

**Comment by s1037989** [comment]
I made the changes but posted them to a [separate branch](https://github.com/jhthorsen/app-git-ship/commit/a437854a4d9ba4b99fdf5289c028fb48fc936f91), just mainly to not pollute the master branch in case I misunderstood something.  I'm new to working on other people's projects directly (which I appreciate the trust in allowing me to do so!) and so I want to take it just a little bit slowly to get started.  I hope that's OK!

Let me know if this is what you had in mind and if so I'll merge it into master!  Thanks!

**Comment by jhthorsen** [comment]
I think we can change the COPYRIGHT/AUTHOR section in perl.pm to

```
=head1 SEE ALSO

L<App::git::ship>
```

Why have you set 2011? I think the first commit was in 2014.

**Comment by s1037989** [comment]
Oh, ha-ha!  I was just going off your example in this issue.  It certainly would have been logical to look up the first commit.  I just figured you might have started this _long_ ago, even if very rudimentary.

54b03230974d3d420de03125722c3a81f1e9f506

Shall I push this commit to master?

**Comment by jhthorsen** [comment]
Ship it! :+1: :smile:
