### ISSUE TITLE
List of contributors missing

### ISSUE THREAD

**Issue by Tekki** [jhthorsen/app-git-ship#21]
There is no list of contributors in published code. Technically,
```
META_MERGE => {
  x_contributors => [...],
}
```
is missing in `Makefile.PL`.
I think we should extract them from the pod and not from `git log`.

**Comment by jhthorsen** [comment]
I like it, but I don't know how to do it 😞

**Comment by Tekki** [comment]
There is a difficulty because we only create Makefile.PL if there is a cpanfile.
Makefile.PL is another place where we should care more about UTF-8.
