### ISSUE TITLE
No rule to make target 'script/git-ship.bak'

### ISSUE THREAD

**Issue by eserte** [jhthorsen/app-git-ship#29]
Build fails:
```
Output from '/usr/bin/make':

cp lib/App/git/ship/perl.pm blib/lib/App/git/ship/perl.pm
cp lib/App/git/ship.pm blib/lib/App/git/ship.pm
make: *** No rule to make target 'script/git-ship.bak', needed by 'blib/script/git-ship.bak'.  Stop.
```

Probably the .bak file here should be removed:
https://metacpan.org/source/JHTHORSEN/App-git-ship-0.34/Makefile.PL#L10

**Comment by jhthorsen** [comment]
Wow! Wonder how that got there...

Anyways - Fixed in 56f857276ac51fa0ca4f31900b5e8d399f53c2f2

Thanks 👍
